// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyepvfffmjbjnkfwfyha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZXB2ZmZmbWpiam5rZndmeWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDE5NTQsImV4cCI6MjA3MzU3Nzk1NH0.Fd50ip2ZD1v2AkmvUfh-y2LYzi4dUezPTALxJycZPkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});